services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spotify-backend-dev
    env_file:
      - .env
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: spotify-backend-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass Senha123
    