services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-api-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3333}:3333"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - spotify-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3333/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: spotify-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - spotify-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  spotify-network:
    driver: bridge
